mode: auto

favicon: /favicon.ico

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: 很遗憾，咱没写啥目录
  collapse: true

social:
  - name: GitHub
    link: https://github.com/liluoao
    icon: ri:github-line
    color: "#6e5494"
  - name: E-Mail
    link: mailto:liluoao@qq.com
    icon: ri:mail-line
    color: "#8E71C1"
  - name: 哔哩哔哩
    link: https://space.bilibili.com/19377772
    icon: ri:bilibili-line
    color: "#FF8EB3"
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=121449072
    icon: ri:netease-cloud-music-line
    color: "#C20C0C"
  - name: 知乎
    link: https://www.zhihu.com/people/li-luo-ao/
    icon: ri:zhihu-line
    color: "#0084FF"
  - name: Twitter
    link: https://twitter.com/easonlee82
    icon: ri:twitter-line
    color: "#1da1f2"

pages:

avatar:
  enable: true
  url: https://i.imgtg.com/2022/08/09/AR3SY.jpg

archive:
  last_word: 无了无了_(:з」∠)_

wordcloud:
  enable: true

banner:
  enable: true
  title: 码之气三段

reward:
  enable: false

footer:
  since: 2018
  icon:
    name: ri:heart-line
    animated: true
    color: "#ff0000"

comment:
  enable: false

github_issues:
  enable: false
  username: liluoao
  repository: blog-source
  filters: is:issue

post_edit:
  enable: true
  url: https://github.com/liluoao/blog-source/tree/master/source/

say:
  api: https://el-bot-api.vercel.app/api/words/young
  hitokoto:
    enable: false

post_meta:
  item_text: false
  created_at: true
  updated_at: false
  categories: true
  tags: false
