mode: auto

# image setting
favicon: /favicon.ico
avatar:
  enable: true
  url: https://i.imgtg.com/2022/08/09/AR3SY.jpg
bg_image:
  enable: false
  url: https://i.imgtg.com/2022/08/24/K31LD.jpg
  dark: https://i.imgtg.com/2022/08/24/K3FcG.jpg

toc:
  list_number: true
  max_depth: 6
  min_depth: 1
  placeholder: 暂无目录
  collapse: true

archive:
  last_word: 感谢观看

banner:
  enable: true
  title: 大梦成空

reward:
  enable: false

footer:
  since: 2018
  icon:
    name: ri:heart-line
    animated: true
    color: "#ff0000"
  powered:
    enable: true

comment:
  enable: false

github_issues:
  enable: false
  username: liluoao
  repository: blog-source
  filters: is:issue

# 名言
say:
  api: https://cdn.jsdelivr.net/gh/ElpsyCN/say@gh-pages/sentences.json
  hitokoto:
    enable: true
    api: https://v1.hitokoto.cn

post_meta:
  item_text: false
  created_at: true
  updated_at: false
  categories: true
  tags: false

# 透明度
post_card:
  opacity: 0.5

# edit link
post_edit:
  enable: true
  url: https://github.com/liluoao/blog-source/tree/master/source/

# 默哀
mourn:
  enable: true
  days:
    - 4-4
    - 5-12
    - 9-18

# Algorithmically generated triangle art
# https://github.com/qrohlf/trianglify
trianglify:
  enable: true
  cellSize: 75
  width: 1980
  height: 1600
  palette: '["YlGnBu", "GnBu", "Purples", "Blues"]'
  opacity: 0.5

# Material Design Cursors
cursor:
  enable: true

# category color
categories:
  Laravel: '#F4645F'
  Vue: '#4fc08d'
  PHP框架: '#8892BF'
  Database: '#3776ab'
  设计模式: '#ff9933'
  工具: '#5298d1'
  分享: '#ff66ff'

wordcloud:
  enable: true

# social link
social:
  - name: GitHub
    link: https://github.com/liluoao
    icon: ri:github-line
    color: "#6e5494"
  - name: E-Mail
    link: mailto:liluoao@qq.com
    icon: ri:mail-line
    color: "#8E71C1"
  - name: 哔哩哔哩
    link: https://space.bilibili.com/19377772
    icon: ri:bilibili-line
    color: "#FF8EB3"
  - name: 网易云音乐
    link: https://music.163.com/#/user/home?id=121449072
    icon: ri:netease-cloud-music-line
    color: "#C20C0C"
  - name: 知乎
    link: https://www.zhihu.com/people/li-luo-ao/
    icon: ri:zhihu-line
    color: "#0084FF"
  - name: Twitter
    link: https://twitter.com/easonlee82
    icon: ri:twitter-line
    color: "#1da1f2"

# 侧边栏链接
pages: