clone_depth: 5

environment:
    access_token:
        secure: 855kciMXrCGEcKW+P87C5nMrvYN47FH/Zjz9yHjZ53yeijLyb6/0oZ4CVv7j0VbE
    nodejs_version: "18"  # 指定 Node.js 版本

# 安装依赖
install:
    - ps: Install-Product node $env:nodejs_version
    - node --version
    - npm --version
    - npm i npm@latest -g
    - npm install
    - npm install hexo-cli -g

build: off  # 关闭默认的 MSBuild 构建

# 构建脚本
build_script:
    - ps: hexo generate
    
artifacts:
    - path: public
    
# 部署脚本
deploy_script:
    - ps: |
        git config --global credential.helper store
        Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
        git config --global user.email $env:GIT_USER_EMAIL
        git config --global user.name $_NAME

        $targetRepo = $env:STATIC_SITE_REPO
        $targetBranch = $env:TARGET_BRANCH
        $tempDir = "$env:TEMP\static-site"
        
        if (Test-Path $tempDir) {
            Remove-Item -Recurse -Force $tempDir
        }
        
        git clone --depth 5 -q --branch=$targetBranch $targetRepo $tempDir

        Set-Location $tempDir
        Get-ChildItem -Recurse | Remove-Item -Recurse -Force

        Copy-Item -Recurse "$env:APPVEYOR_BUILD_FOLDER\public\*" $tempDir

        git add -A
        git commit -m "Update Static Site"
        git push origin $targetBranch
