# Header
menu:
  首页: /
  文章列表: /archives
  Laravel: /categories/laravel
  Phalcon: /categories/phalcon
  Wechat: /categories/wechat
  关于作者: /me.html

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: left
widgets:
- recent_posts
- category
- tag
- archive

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 - category
 - tagcloud
 - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter: liluoao
google_plus:
fb_admins:
fb_app_id:
